### ISSUE TITLE
[REQUEST] Support for amazon.*

### ISSUE THREAD

**Issue by Spectroxx** [raineymarkr/Amazon-to-Anna#1]
Here's a list of Amazon domains for other non US countries.

- [ ] amazon.ca
- [ ] amazon.cn
- [ ] amazon.co.jp
- [ ] amazon.com
- [ ] amazon.com.au
- [ ] amazon.com.mx
- [ ] amazon.co.uk
- [ ] amazon.de
- [ ] amazon.es
- [ ] amazon.eu
- [ ] amazon.fr
- [ ] amazon.in
- [ ] amazon.it
- [ ] amazon.nl
- [ ] amazon.sa

**Comment by raineymarkr** [comment]
Thanks for the catch! I've added support for international urls.

https://github.com/raineymarkr/Amazon-to-Anna/releases/tag/2.0
